"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useSnackbar } from "@/context/SnackbarContext";
import {
  fetchEventDetail,
  fetchPlayerEventSummary,
} from "@/services/eventService";
import type {
  FetchEventDetailErrorResponse,
  FetchPlayerEventSummaryErrorResponse,
  PlayerEventSummary,
} from "@/types/event";
import {
  downloadImage,
  formatWinPercentage,
  generateYourResultPng,
} from "@/utils/shareStandingsImage";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const DEFAULT_OVERLAY_OPACITY = 0.45;
const PREVIEW_WIDTH = 320;

interface PhotoTransform {
  scale: number;
  offsetX: number;
  offsetY: number;
}

interface ShareYourResultClientProps {
  eventGuid: string;
}

function YourResultStatsOverlay({
  eventName,
  summary,
}: {
  eventName: string;
  summary: PlayerEventSummary;
}) {
  const stats = [
    { label: "Win Rate", value: formatWinPercentage(summary.win_percentage) },
    { label: "Position", value: `#${summary.rank}` },
    { label: "Matches Played", value: String(summary.matches_played) },
    { label: "Total Win", value: String(summary.wins) },
    { label: "Total Loss", value: String(summary.loss) },
    { label: "Total Points", value: String(summary.total_points) },
  ];

  return (
    <div className="pointer-events-none absolute inset-x-0 bottom-0 z-10 flex flex-col items-center gap-4 px-5 pb-10 pt-8 text-center text-white">
      <div className="flex w-full min-w-0 items-center justify-between gap-[5px] px-1">
        <p className="min-w-0 flex-1 text-left text-[9px] font-semibold leading-snug text-white/80 line-clamp-2 break-words">
          {eventName}
        </p>
        <p className="shrink-0 text-lg font-black tracking-tight">RALLYRANK</p>
      </div>
      <div className="grid w-full grid-cols-3 gap-x-2 gap-y-2.5">
        {stats.map((stat) => (
          <div key={stat.label} className="flex flex-col items-center gap-0.5">
            <span className="text-[9.5px] font-semibold uppercase leading-tight text-white/70">
              {stat.label}
            </span>
            <span className="text-[19px] font-bold">{stat.value}</span>
          </div>
        ))}
      </div>
      <p className="text-[11px] text-white/50">Generated by RallyRank</p>
    </div>
  );
}

function getTouchDistance(touches: React.TouchList) {
  if (touches.length < 2) return 0;
  const dx = touches[0].clientX - touches[1].clientX;
  const dy = touches[0].clientY - touches[1].clientY;
  return Math.hypot(dx, dy);
}

export default function ShareYourResultClient({
  eventGuid,
}: ShareYourResultClientProps) {
  const router = useRouter();
  const { showSnackbar } = useSnackbar();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const dragStartRef = useRef<{
    x: number;
    y: number;
    offsetX: number;
    offsetY: number;
  } | null>(null);
  const pinchStartRef = useRef<{ distance: number; scale: number } | null>(
    null,
  );

  const [eventName, setEventName] = useState("");
  const [summary, setSummary] = useState<PlayerEventSummary | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [photoTransform, setPhotoTransform] = useState<PhotoTransform>({
    scale: 1,
    offsetX: 0,
    offsetY: 0,
  });
  const [overlayOpacity, setOverlayOpacity] = useState(
    DEFAULT_OVERLAY_OPACITY,
  );
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [photoError, setPhotoError] = useState<string | null>(null);

  useEffect(() => {
    if (!eventGuid.trim()) {
      showSnackbar("Event not found for this session.");
      router.back();
      return;
    }

    let cancelled = false;

    (async () => {
      setIsLoading(true);
      try {
        const [eventRes, summaryRes] = await Promise.all([
          fetchEventDetail(eventGuid),
          fetchPlayerEventSummary(eventGuid),
        ]);
        if (cancelled) return;

        if (summaryRes.data.matches_played <= 0) {
          showSnackbar("Your standing is not available yet.");
          router.back();
          return;
        }

        setEventName(eventRes.data.name);
        setSummary(summaryRes.data);
      } catch (e) {
        if (cancelled) return;
        const err = e as
          | FetchEventDetailErrorResponse
          | FetchPlayerEventSummaryErrorResponse
          | Error;
        showSnackbar(
          "message" in err && typeof err.message === "string"
            ? err.message
            : "Could not load your result.",
        );
        router.back();
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [eventGuid, router, showSnackbar]);

  useEffect(() => {
    return () => {
      if (photoPreview) URL.revokeObjectURL(photoPreview);
    };
  }, [photoPreview]);

  function resetPhotoTransform() {
    setPhotoTransform({ scale: 1, offsetX: 0, offsetY: 0 });
  }

  function handleSelectPhotoClick() {
    fileInputRef.current?.click();
  }

  function handlePhotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!ALLOWED_TYPES.includes(file.type)) {
      setPhotoError("Only JPG, PNG, or WebP files are allowed.");
      return;
    }

    setPhotoError(null);
    if (photoPreview) URL.revokeObjectURL(photoPreview);
    setPhotoPreview(URL.createObjectURL(file));
    resetPhotoTransform();
    setOverlayOpacity(DEFAULT_OVERLAY_OPACITY);
  }

  function handlePointerDown(e: React.PointerEvent<HTMLDivElement>) {
    if (!photoPreview) return;
    dragStartRef.current = {
      x: e.clientX,
      y: e.clientY,
      offsetX: photoTransform.offsetX,
      offsetY: photoTransform.offsetY,
    };
    e.currentTarget.setPointerCapture(e.pointerId);
  }

  function handlePointerMove(e: React.PointerEvent<HTMLDivElement>) {
    if (!dragStartRef.current) return;
    setPhotoTransform((current) => ({
      ...current,
      offsetX:
        dragStartRef.current!.offsetX + (e.clientX - dragStartRef.current!.x),
      offsetY:
        dragStartRef.current!.offsetY + (e.clientY - dragStartRef.current!.y),
    }));
  }

  function handlePointerUp() {
    dragStartRef.current = null;
  }

  function handleTouchStart(e: React.TouchEvent<HTMLDivElement>) {
    if (!photoPreview || e.touches.length < 2) return;
    pinchStartRef.current = {
      distance: getTouchDistance(e.touches),
      scale: photoTransform.scale,
    };
  }

  function handleTouchMove(e: React.TouchEvent<HTMLDivElement>) {
    if (!photoPreview || !pinchStartRef.current || e.touches.length < 2) return;
    const distance = getTouchDistance(e.touches);
    if (distance <= 0) return;
    const nextScale =
      pinchStartRef.current.scale * (distance / pinchStartRef.current.distance);
    setPhotoTransform((current) => ({
      ...current,
      scale: Math.min(3, Math.max(1, nextScale)),
    }));
  }

  function handleTouchEnd() {
    pinchStartRef.current = null;
  }

  async function handleShare() {
    if (!summary || isSubmitting || !previewRef.current) return;

    setIsSubmitting(true);
    try {
      const previewWidth = previewRef.current.clientWidth || PREVIEW_WIDTH;
      const ratio = 1080 / previewWidth;

      const blob = await generateYourResultPng({
        eventName,
        summary: {
          winPercentage: summary.win_percentage,
          rank: summary.rank,
          matchesPlayed: summary.matches_played,
          wins: summary.wins,
          loss: summary.loss,
          totalPoints: summary.total_points,
        },
        backgroundImageSrc: photoPreview ?? undefined,
        overlayOpacity: photoPreview ? overlayOpacity : undefined,
        backgroundTransform: photoPreview
          ? {
              scale: photoTransform.scale,
              offsetX: photoTransform.offsetX * ratio,
              offsetY: photoTransform.offsetY * ratio,
            }
          : undefined,
      });

      downloadImage(
        blob,
        `${eventName.replace(/\s+/g, "-").toLowerCase()}-my-result.jpg`,
      );
      showSnackbar("Your result image downloaded.");
    } catch {
      showSnackbar("Could not share your result.");
    } finally {
      setIsSubmitting(false);
    }
  }

  if (isLoading || !summary) {
    return (
      <main
        className="flex flex-1 items-center justify-center px-6"
        style={{ paddingTop: "64px", paddingBottom: "120px" }}
      >
        <p className="text-sm text-[#71717A]">Loading preview…</p>
      </main>
    );
  }

  return (
    <>
      <main
        className="flex flex-1 flex-col gap-4 px-6"
        style={{ paddingTop: "80px", paddingBottom: "120px" }}
      >
        <div
          ref={previewRef}
          className="relative mx-auto w-[320px] touch-none overflow-hidden bg-[#18181B]"
          style={{ width: "320px", height: `${(320 * 16) / 9}px` }}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerCancel={handlePointerUp}
          onTouchStart={handleTouchStart}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
        >
          {photoPreview ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={photoPreview}
              alt="Selected background"
              className="absolute h-full w-full origin-center object-cover"
              style={{
                transform: `translate(${photoTransform.offsetX}px, ${photoTransform.offsetY}px) scale(${photoTransform.scale})`,
              }}
              draggable={false}
            />
          ) : (
            <div className="absolute inset-0 bg-[#18181B]" />
          )}
          {photoPreview ? (
            <div
              className="absolute inset-0"
              style={{ background: `rgba(0, 0, 0, ${overlayOpacity})` }}
            />
          ) : null}
          <YourResultStatsOverlay eventName={eventName} summary={summary} />
        </div>

        {photoPreview ? (
          <p className="text-center text-xs text-[#71717A]">
            Pinch to resize, drag to move
          </p>
        ) : null}

        <button
          type="button"
          onClick={handleSelectPhotoClick}
          className="w-full rounded-full text-sm font-semibold text-[#18181B]"
          style={{ background: "#F4F4F5", height: "56px" }}
        >
          Select photos
        </button>
        {photoError ? (
          <p className="-mt-2 text-xs text-red-500">{photoError}</p>
        ) : null}

        {photoPreview ? (
          <div className="flex flex-col gap-2">
            <label
              htmlFor="overlay-opacity"
              className="text-sm font-medium text-[#18181B]"
            >
              Opacity: {Math.round(overlayOpacity * 100)}%
            </label>
            <input
              id="overlay-opacity"
              type="range"
              min={0}
              max={80}
              value={Math.round(overlayOpacity * 100)}
              onChange={(e) =>
                setOverlayOpacity(Number(e.target.value) / 100)
              }
              className="w-full accent-[#9FE870]"
            />
          </div>
        ) : null}

        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/png,image/webp"
          className="hidden"
          onChange={handlePhotoChange}
        />
      </main>

      <div
        className="fixed bottom-0 left-0 right-0 z-50 max-w-[448px] mx-auto px-6 py-4 pb-8"
        style={{ background: "#FFFFFF", borderTop: "1px solid #F4F4F5" }}
      >
        <button
          type="button"
          onClick={handleShare}
          disabled={isSubmitting}
          className="w-full rounded-full text-base font-semibold text-[#121212] disabled:cursor-not-allowed disabled:opacity-50"
          style={{ background: "#9FE870", height: "56px" }}
        >
          {isSubmitting ? "Generating…" : "Share"}
        </button>
      </div>
    </>
  );
}
