"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useSnackbar } from "@/context/SnackbarContext";
import { fetchEventDetail, fetchEventStandings } from "@/services/eventService";
import type {
  EventStandingRow,
  EventStandingsType,
  FetchEventDetailErrorResponse,
  FetchEventStandingsErrorResponse,
} from "@/types/event";
import {
  captureElementAsPng,
  downloadImage,
  formatShareStandingStat,
  standingsTypeLabel,
  type ShareStandingRow,
} from "@/utils/shareStandingsImage";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const DEFAULT_OVERLAY_OPACITY = 0.45;
const MEDAL_TEXT_COLORS = ["#EAB308", "#A1A1AA", "#FB923C"];

interface PhotoTransform {
  scale: number;
  offsetX: number;
  offsetY: number;
}

interface ShareMatchResultClientProps {
  eventGuid: string;
  standingsType: EventStandingsType;
}

function formatWinRate(wins: number, matchesPlayed: number) {
  if (matchesPlayed <= 0) return "—";
  return `${Math.round((wins / matchesPlayed) * 100)}%`;
}

function mapToShareRows(rows: EventStandingRow[]): ShareStandingRow[] {
  return rows.map((row) => ({
    rank: row.rank,
    name: row.user.name.trim() || row.user.email,
    mp: row.matches_played,
    wins: row.wins,
    scoreDiff: row.score_diff,
    winPct: formatWinRate(row.wins, row.matches_played),
    total_points: row.total_points,
  }));
}

function MatchResultStandingsOverlay({
  eventName,
  standingsType,
  top3,
}: {
  eventName: string;
  standingsType: EventStandingsType;
  top3: ShareStandingRow[];
}) {
  return (
    <div className="pointer-events-none absolute inset-x-0 bottom-0 z-10 flex flex-col items-center gap-4 px-5 pb-10 pt-8 text-center text-white">
      <div className="flex w-full min-w-0 items-center justify-between gap-[5px] px-1">
        <p className="min-w-0 flex-1 text-left text-[9px] font-semibold leading-snug text-white/80 line-clamp-2 break-words">
          {eventName}
        </p>
        <p className="shrink-0 text-lg font-black tracking-tight">RALLYRANK</p>
      </div>
      <p className="text-[10px] font-medium text-white/60">
        Top 3 · {standingsTypeLabel(standingsType)}
      </p>
      <div className="flex w-full flex-col gap-2">
        {top3.map((row) => (
          <div
            key={row.rank}
            className="flex items-center gap-2 rounded-lg bg-white/10 px-2.5 py-2"
          >
            <span
              className="w-4 shrink-0 text-left text-[13px] font-bold"
              style={{ color: MEDAL_TEXT_COLORS[row.rank - 1] ?? "#FFFFFF" }}
            >
              {row.rank}
            </span>
            <span className="min-w-0 flex-1 truncate text-left text-[11px] font-semibold">
              {row.name}
            </span>
            <span className="shrink-0 text-[9px] font-semibold text-white/70">
              {formatShareStandingStat(row, standingsType)}
            </span>
          </div>
        ))}
      </div>
      <p className="text-[11px] text-white/50">Generated by RallyRank</p>
    </div>
  );
}

function getTouchDistance(touches: React.TouchList) {
  if (touches.length < 2) return 0;
  const dx = touches[0].clientX - touches[1].clientX;
  const dy = touches[0].clientY - touches[1].clientY;
  return Math.hypot(dx, dy);
}

export default function ShareMatchResultClient({
  eventGuid,
  standingsType,
}: ShareMatchResultClientProps) {
  const router = useRouter();
  const { showSnackbar } = useSnackbar();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const dragStartRef = useRef<{
    x: number;
    y: number;
    offsetX: number;
    offsetY: number;
  } | null>(null);
  const pinchStartRef = useRef<{ distance: number; scale: number } | null>(
    null,
  );

  const [eventName, setEventName] = useState("");
  const [top3, setTop3] = useState<ShareStandingRow[]>([]);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [photoTransform, setPhotoTransform] = useState<PhotoTransform>({
    scale: 1,
    offsetX: 0,
    offsetY: 0,
  });
  const [overlayOpacity, setOverlayOpacity] = useState(
    DEFAULT_OVERLAY_OPACITY,
  );
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [photoError, setPhotoError] = useState<string | null>(null);

  useEffect(() => {
    if (!eventGuid.trim()) {
      showSnackbar("Event not found for this session.");
      router.back();
      return;
    }

    let cancelled = false;

    (async () => {
      setIsLoading(true);
      try {
        const [eventRes, standingsRes] = await Promise.all([
          fetchEventDetail(eventGuid),
          fetchEventStandings({ event_guid: eventGuid, type: standingsType }),
        ]);
        if (cancelled) return;

        const rows = mapToShareRows(standingsRes.data.standings).slice(0, 3);
        if (rows.length === 0) {
          showSnackbar("No standings available to share yet.");
          router.back();
          return;
        }

        setEventName(eventRes.data.name);
        setTop3(rows);
      } catch (e) {
        if (cancelled) return;
        const err = e as
          | FetchEventDetailErrorResponse
          | FetchEventStandingsErrorResponse
          | Error;
        showSnackbar(
          "message" in err && typeof err.message === "string"
            ? err.message
            : "Could not load match result.",
        );
        router.back();
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [eventGuid, router, showSnackbar, standingsType]);

  function resetPhotoTransform() {
    setPhotoTransform({ scale: 1, offsetX: 0, offsetY: 0 });
  }

  function handleSelectPhotoClick() {
    fileInputRef.current?.click();
  }

  function handlePhotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!ALLOWED_TYPES.includes(file.type)) {
      setPhotoError("Only JPG, PNG, or WebP files are allowed.");
      return;
    }

    setPhotoError(null);
    const reader = new FileReader();
    reader.onload = (evt) => {
      const dataUrl = evt.target?.result;
      if (typeof dataUrl !== "string") return;
      setPhotoPreview(dataUrl);
      resetPhotoTransform();
      setOverlayOpacity(DEFAULT_OVERLAY_OPACITY);
    };
    reader.readAsDataURL(file);
  }

  function handlePointerDown(e: React.PointerEvent<HTMLDivElement>) {
    if (!photoPreview) return;
    dragStartRef.current = {
      x: e.clientX,
      y: e.clientY,
      offsetX: photoTransform.offsetX,
      offsetY: photoTransform.offsetY,
    };
    e.currentTarget.setPointerCapture(e.pointerId);
  }

  function handlePointerMove(e: React.PointerEvent<HTMLDivElement>) {
    if (!dragStartRef.current) return;
    setPhotoTransform((current) => ({
      ...current,
      offsetX:
        dragStartRef.current!.offsetX + (e.clientX - dragStartRef.current!.x),
      offsetY:
        dragStartRef.current!.offsetY + (e.clientY - dragStartRef.current!.y),
    }));
  }

  function handlePointerUp() {
    dragStartRef.current = null;
  }

  function handleTouchStart(e: React.TouchEvent<HTMLDivElement>) {
    if (!photoPreview || e.touches.length < 2) return;
    pinchStartRef.current = {
      distance: getTouchDistance(e.touches),
      scale: photoTransform.scale,
    };
  }

  function handleTouchMove(e: React.TouchEvent<HTMLDivElement>) {
    if (!photoPreview || !pinchStartRef.current || e.touches.length < 2) return;
    const distance = getTouchDistance(e.touches);
    if (distance <= 0) return;
    const nextScale =
      pinchStartRef.current.scale * (distance / pinchStartRef.current.distance);
    setPhotoTransform((current) => ({
      ...current,
      scale: Math.min(3, Math.max(1, nextScale)),
    }));
  }

  function handleTouchEnd() {
    pinchStartRef.current = null;
  }

  async function handleShare() {
    if (top3.length === 0 || isSubmitting || !previewRef.current) return;

    setIsSubmitting(true);
    try {
      const blob = await captureElementAsPng(previewRef.current);

      downloadImage(
        blob,
        `${eventName.replace(/\s+/g, "-").toLowerCase()}-top-3.png`,
      );
      showSnackbar("Match result image downloaded.");
    } catch {
      showSnackbar("Could not share match result.");
    } finally {
      setIsSubmitting(false);
    }
  }

  if (isLoading || top3.length === 0) {
    return (
      <main
        className="flex flex-1 items-center justify-center px-6"
        style={{ paddingTop: "64px", paddingBottom: "120px" }}
      >
        <p className="text-sm text-[#71717A]">Loading preview…</p>
      </main>
    );
  }

  return (
    <main
      className="flex flex-1 flex-col gap-4 px-6"
      style={{ paddingTop: "80px", paddingBottom: "48px" }}
    >
        <div
          ref={previewRef}
          className="relative mx-auto w-[320px] touch-none overflow-hidden bg-[#18181B]"
          style={{ width: "320px", height: `${(320 * 16) / 9}px` }}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerCancel={handlePointerUp}
          onTouchStart={handleTouchStart}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
        >
          {photoPreview ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={photoPreview}
              alt="Selected background"
              className="absolute h-full w-full origin-center object-cover"
              style={{
                transform: `translate(${photoTransform.offsetX}px, ${photoTransform.offsetY}px) scale(${photoTransform.scale})`,
              }}
              draggable={false}
            />
          ) : null}
          <div
            className="absolute inset-0"
            style={{ background: `rgba(0, 0, 0, ${overlayOpacity})` }}
          />
          <MatchResultStandingsOverlay
            eventName={eventName}
            standingsType={standingsType}
            top3={top3}
          />
        </div>

        {photoPreview ? (
          <p className="text-center text-xs text-[#71717A]">
            Pinch to resize, drag to move
          </p>
        ) : null}

        <button
          type="button"
          onClick={handleSelectPhotoClick}
          className="w-full rounded-full text-sm font-semibold text-[#18181B]"
          style={{ background: "#F4F4F5", height: "56px" }}
        >
          Select photos
        </button>

        <button
          type="button"
          onClick={handleShare}
          disabled={isSubmitting}
          className="w-full rounded-full text-base font-semibold text-[#121212] disabled:cursor-not-allowed disabled:opacity-50"
          style={{ background: "#9FE870", height: "56px" }}
        >
          {isSubmitting ? "Generating…" : "Share"}
        </button>

        {photoError ? (
          <p className="-mt-2 text-xs text-red-500">{photoError}</p>
        ) : null}

        {photoPreview ? (
          <div className="flex flex-col gap-2">
            <label
              htmlFor="match-overlay-opacity"
              className="text-sm font-medium text-[#18181B]"
            >
              Opacity: {Math.round(overlayOpacity * 100)}%
            </label>
            <input
              id="match-overlay-opacity"
              type="range"
              min={0}
              max={80}
              value={Math.round(overlayOpacity * 100)}
              onChange={(e) =>
                setOverlayOpacity(Number(e.target.value) / 100)
              }
              className="w-full accent-[#9FE870]"
            />
          </div>
        ) : null}

        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/png,image/webp"
          className="hidden"
          onChange={handlePhotoChange}
        />
      </main>
  );
}
