"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useSnackbar } from "@/context/SnackbarContext";
import { usePhotoTransform } from "@/hooks/usePhotoTransform";
import {
  fetchEventDetail,
  fetchPlayerEventSummary,
} from "@/services/eventService";
import type {
  FetchEventDetailErrorResponse,
  FetchPlayerEventSummaryErrorResponse,
  PlayerEventSummary,
} from "@/types/event";
import {
  captureElementAsPng,
  downloadImage,
  formatWinPercentage,
  isMobileShareSupported,
  resizeImageDataUrl,
} from "@/utils/shareStandingsImage";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const DEFAULT_OVERLAY_OPACITY = 0.45;

interface ShareYourResultClientProps {
  eventGuid: string;
}

function YourResultStatsOverlay({
  eventName,
  summary,
}: {
  eventName: string;
  summary: PlayerEventSummary;
}) {
  const stats = [
    { label: "Win Rate", value: formatWinPercentage(summary.win_percentage) },
    { label: "Position", value: `#${summary.rank}` },
    { label: "Matches Played", value: String(summary.matches_played) },
    { label: "Total Win", value: String(summary.wins) },
    { label: "Total Loss", value: String(summary.loss) },
    { label: "Total Points", value: String(summary.total_points) },
  ];

  return (
    <div className="pointer-events-none absolute inset-x-0 bottom-0 z-10 flex flex-col items-center gap-4 px-5 pb-10 pt-8 text-center text-white">
      <div className="flex w-full min-w-0 items-center justify-between gap-[5px] px-1">
        <p className="min-w-0 flex-1 text-left text-[9px] font-semibold leading-snug text-white/80 line-clamp-2 break-words">
          {eventName}
        </p>
        <p className="shrink-0 text-lg font-black tracking-tight">RALLYRANK</p>
      </div>
      <div className="grid w-full grid-cols-3 gap-x-2 gap-y-2.5">
        {stats.map((stat) => (
          <div key={stat.label} className="flex flex-col items-center gap-0.5">
            <span className="text-[9.5px] font-semibold uppercase leading-tight text-white/70">
              {stat.label}
            </span>
            <span className="text-[19px] font-bold">{stat.value}</span>
          </div>
        ))}
      </div>
      <p className="text-[11px] text-white/50">Generated by RallyRank</p>
    </div>
  );
}

export default function ShareYourResultClient({
  eventGuid,
}: ShareYourResultClientProps) {
  const router = useRouter();
  const { showSnackbar } = useSnackbar();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const {
    photoTransform,
    photoImgRef,
    previewGestureProps,
    resetPhotoTransform,
    getPhotoTransform,
  } = usePhotoTransform();

  const [eventName, setEventName] = useState("");
  const [summary, setSummary] = useState<PlayerEventSummary | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [overlayOpacity, setOverlayOpacity] = useState(
    DEFAULT_OVERLAY_OPACITY,
  );
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [photoError, setPhotoError] = useState<string | null>(null);

  useEffect(() => {
    if (!eventGuid.trim()) {
      showSnackbar("Event not found for this session.");
      router.back();
      return;
    }

    let cancelled = false;

    (async () => {
      setIsLoading(true);
      try {
        const [eventRes, summaryRes] = await Promise.all([
          fetchEventDetail(eventGuid),
          fetchPlayerEventSummary(eventGuid),
        ]);
        if (cancelled) return;

        if (summaryRes.data.matches_played <= 0) {
          showSnackbar("Your standing is not available yet.");
          router.back();
          return;
        }

        setEventName(eventRes.data.name);
        setSummary(summaryRes.data);
      } catch (e) {
        if (cancelled) return;
        const err = e as
          | FetchEventDetailErrorResponse
          | FetchPlayerEventSummaryErrorResponse
          | Error;
        showSnackbar(
          "message" in err && typeof err.message === "string"
            ? err.message
            : "Could not load your result.",
        );
        router.back();
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [eventGuid, router, showSnackbar]);

  function handleSelectPhotoClick() {
    fileInputRef.current?.click();
  }

  function handlePhotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!ALLOWED_TYPES.includes(file.type)) {
      setPhotoError("Only JPG, PNG, or WebP files are allowed.");
      return;
    }

    setPhotoError(null);
    const reader = new FileReader();
    reader.onload = async (evt) => {
      const dataUrl = evt.target?.result;
      if (typeof dataUrl !== "string") return;
      const resized = await resizeImageDataUrl(dataUrl);
      setPhotoPreview(resized);
      resetPhotoTransform();
      setOverlayOpacity(DEFAULT_OVERLAY_OPACITY);
    };
    reader.readAsDataURL(file);
  }

  async function handleShare() {
    if (!summary || isSubmitting || !previewRef.current) return;

    setIsSubmitting(true);
    try {
      const blob = await captureElementAsPng(
        previewRef.current,
        1080,
        photoPreview,
        getPhotoTransform(),
        overlayOpacity,
      );
      const filename = `${eventName.replace(/\s+/g, "-").toLowerCase()}-my-result.png`;
      const file = new File([blob], filename, { type: "image/png" });

      if (isMobileShareSupported(file)) {
        await navigator.share({ files: [file], title: eventName });
      } else {
        downloadImage(blob, filename);
        showSnackbar("Your result image downloaded.");
      }
    } catch (err) {
      if (err instanceof Error && err.name !== "AbortError") {
        showSnackbar("Could not share your result.");
      }
    } finally {
      setIsSubmitting(false);
    }
  }

  if (isLoading || !summary) {
    return (
      <main
        className="flex flex-1 items-center justify-center px-6"
        style={{ paddingTop: "64px", paddingBottom: "120px" }}
      >
        <p className="text-sm text-[#71717A]">Loading preview…</p>
      </main>
    );
  }

  return (
    <main
      className="flex flex-1 flex-col gap-4 px-6"
      style={{ paddingTop: "80px", paddingBottom: "48px" }}
    >
      <div
        className="relative mx-auto"
        style={{ width: "320px", height: `${(320 * 16) / 9}px` }}
      >
        {!photoPreview && (
          <div className="absolute inset-0 bg-[#18181B]" />
        )}
        <div ref={previewRef} {...previewGestureProps}>
          {photoPreview ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              ref={photoImgRef}
              src={photoPreview}
              alt="Selected background"
              className="absolute h-full w-full origin-center object-cover"
              style={{
                transform: `translate3d(${photoTransform.offsetX}px, ${photoTransform.offsetY}px, 0) scale(${photoTransform.scale})`,
              }}
              draggable={false}
              data-capture-ignore="true"
            />
          ) : null}
          {photoPreview ? (
            <div
              className="absolute inset-0"
              style={{ background: `rgba(0, 0, 0, ${overlayOpacity})` }}
              data-capture-ignore="true"
            />
          ) : null}
          <YourResultStatsOverlay eventName={eventName} summary={summary} />
        </div>
      </div>

      {photoPreview ? (
        <p className="text-center text-xs text-[#71717A]">
          Pinch to resize, drag to move
        </p>
      ) : null}

      <button
        type="button"
        onClick={handleSelectPhotoClick}
        className="w-full rounded-full text-sm font-semibold text-[#18181B]"
        style={{ background: "#F4F4F5", height: "56px" }}
      >
        Select photos
      </button>

      <button
        type="button"
        onClick={handleShare}
        disabled={isSubmitting}
        className="w-full rounded-full text-base font-semibold text-[#121212] disabled:cursor-not-allowed disabled:opacity-50"
        style={{ background: "#9FE870", height: "56px" }}
      >
        {isSubmitting ? "Generating…" : "Share"}
      </button>

      {photoError ? (
        <p className="-mt-2 text-xs text-red-500">{photoError}</p>
      ) : null}

      {photoPreview ? (
        <div className="flex flex-col gap-2">
          <label
            htmlFor="overlay-opacity"
            className="text-sm font-medium text-[#18181B]"
          >
            Opacity: {Math.round(overlayOpacity * 100)}%
          </label>
          <input
            id="overlay-opacity"
            type="range"
            min={0}
            max={80}
            value={Math.round(overlayOpacity * 100)}
            onChange={(e) => setOverlayOpacity(Number(e.target.value) / 100)}
            className="w-full accent-[#9FE870]"
          />
        </div>
      ) : null}

      <input
        ref={fileInputRef}
        type="file"
        accept="image/jpeg,image/png,image/webp"
        className="hidden"
        onChange={handlePhotoChange}
      />
    </main>
  );
}
