"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useSnackbar } from "@/context/SnackbarContext";
import { usePhotoTransform } from "@/hooks/usePhotoTransform";
import { fetchEventDetail, fetchEventStandings } from "@/services/eventService";
import type {
  EventStandingRow,
  EventStandingsType,
  FetchEventDetailErrorResponse,
  FetchEventStandingsErrorResponse,
} from "@/types/event";
import {
  captureElementAsPng,
  downloadImage,
  formatShareStandingStat,
  isMobileShareSupported,
  resizeImageDataUrl,
  standingsTypeLabel,
  type ShareStandingRow,
} from "@/utils/shareStandingsImage";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const DEFAULT_OVERLAY_OPACITY = 0.45;
const MEDAL_TEXT_COLORS = ["#EAB308", "#A1A1AA", "#FB923C"];

interface ShareMatchResultClientProps {
  eventGuid: string;
  standingsType: EventStandingsType;
}

function formatWinRate(wins: number, matchesPlayed: number) {
  if (matchesPlayed <= 0) return "—";
  return `${Math.round((wins / matchesPlayed) * 100)}%`;
}

function mapToShareRows(rows: EventStandingRow[]): ShareStandingRow[] {
  return rows.map((row) => ({
    rank: row.rank,
    name: row.user.name.trim() || row.user.email,
    mp: row.matches_played,
    wins: row.wins,
    scoreDiff: row.score_diff,
    winPct: formatWinRate(row.wins, row.matches_played),
    total_points: row.total_points,
  }));
}

function MatchResultStandingsOverlay({
  eventName,
  standingsType,
  top3,
}: {
  eventName: string;
  standingsType: EventStandingsType;
  top3: ShareStandingRow[];
}) {
  return (
    <div className="pointer-events-none absolute inset-x-0 bottom-0 z-10 flex flex-col items-center gap-4 px-5 pb-10 pt-8 text-center text-white">
      <div className="flex w-full min-w-0 items-center justify-between gap-[5px] px-1">
        <p className="min-w-0 flex-1 text-left text-[9px] font-semibold leading-snug text-white/80 line-clamp-2 break-words">
          {eventName}
        </p>
        <p className="shrink-0 text-lg font-black tracking-tight">RALLYRANK</p>
      </div>
      <p className="text-[10px] font-medium text-white/60">
        Top 3 · {standingsTypeLabel(standingsType)}
      </p>
      <div className="flex w-full flex-col gap-2">
        {top3.map((row) => (
          <div
            key={row.rank}
            className="flex items-center gap-2 rounded-lg bg-white/10 px-2.5 py-2"
          >
            <span
              className="w-4 shrink-0 text-left text-[13px] font-bold"
              style={{ color: MEDAL_TEXT_COLORS[row.rank - 1] ?? "#FFFFFF" }}
            >
              {row.rank}
            </span>
            <span className="min-w-0 flex-1 truncate text-left text-[11px] font-semibold">
              {row.name}
            </span>
            <span className="shrink-0 text-[9px] font-semibold text-white/70">
              {formatShareStandingStat(row, standingsType)}
            </span>
          </div>
        ))}
      </div>
      <p className="text-[11px] text-white/50">Generated by RallyRank</p>
    </div>
  );
}

export default function ShareMatchResultClient({
  eventGuid,
  standingsType,
}: ShareMatchResultClientProps) {
  const router = useRouter();
  const { showSnackbar } = useSnackbar();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const {
    photoTransform,
    photoImgRef,
    previewGestureProps,
    resetPhotoTransform,
    getPhotoTransform,
  } = usePhotoTransform();

  const [eventName, setEventName] = useState("");
  const [top3, setTop3] = useState<ShareStandingRow[]>([]);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [overlayOpacity, setOverlayOpacity] = useState(DEFAULT_OVERLAY_OPACITY);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [photoError, setPhotoError] = useState<string | null>(null);

  useEffect(() => {
    if (!eventGuid.trim()) {
      showSnackbar("Event not found for this session.");
      router.back();
      return;
    }

    let cancelled = false;

    (async () => {
      setIsLoading(true);
      try {
        const [eventRes, standingsRes] = await Promise.all([
          fetchEventDetail(eventGuid),
          fetchEventStandings({ event_guid: eventGuid, type: standingsType }),
        ]);
        if (cancelled) return;

        const rows = mapToShareRows(standingsRes.data.standings).slice(0, 3);
        if (rows.length === 0) {
          showSnackbar("No standings available to share yet.");
          router.back();
          return;
        }

        setEventName(eventRes.data.name);
        setTop3(rows);
      } catch (e) {
        if (cancelled) return;
        const err = e as
          | FetchEventDetailErrorResponse
          | FetchEventStandingsErrorResponse
          | Error;
        showSnackbar(
          "message" in err && typeof err.message === "string"
            ? err.message
            : "Could not load match result.",
        );
        router.back();
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [eventGuid, router, showSnackbar, standingsType]);

  function handleSelectPhotoClick() {
    fileInputRef.current?.click();
  }

  function handlePhotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!ALLOWED_TYPES.includes(file.type)) {
      setPhotoError("Only JPG, PNG, or WebP files are allowed.");
      return;
    }

    setPhotoError(null);
    const reader = new FileReader();
    reader.onload = async (evt) => {
      const dataUrl = evt.target?.result;
      if (typeof dataUrl !== "string") return;
      const resized = await resizeImageDataUrl(dataUrl);
      setPhotoPreview(resized);
      resetPhotoTransform();
      setOverlayOpacity(DEFAULT_OVERLAY_OPACITY);
    };
    reader.readAsDataURL(file);
  }

  async function handleShare() {
    if (top3.length === 0 || isSubmitting || !previewRef.current) return;

    setIsSubmitting(true);
    try {
      const blob = await captureElementAsPng(
        previewRef.current,
        1080,
        photoPreview,
        getPhotoTransform(),
        overlayOpacity,
      );
      const filename = `${eventName.replace(/\s+/g, "-").toLowerCase()}-top-3.png`;
      const file = new File([blob], filename, { type: "image/png" });

      if (isMobileShareSupported(file)) {
        await navigator.share({ files: [file], title: eventName });
      } else {
        downloadImage(blob, filename);
        showSnackbar("Match result image downloaded.");
      }
    } catch (err) {
      if (err instanceof Error && err.name !== "AbortError") {
        showSnackbar("Could not share match result.");
      }
    } finally {
      setIsSubmitting(false);
    }
  }

  if (isLoading || top3.length === 0) {
    return (
      <main
        className="flex flex-1 items-center justify-center px-6"
        style={{ paddingTop: "64px", paddingBottom: "120px" }}
      >
        <p className="text-sm text-[#71717A]">Loading preview…</p>
      </main>
    );
  }

  return (
    <main
      className="flex flex-1 flex-col gap-4 px-6"
      style={{ paddingTop: "80px", paddingBottom: "48px" }}
    >
      <div
        className="relative mx-auto"
        style={{ width: "320px", height: `${(320 * 16) / 9}px` }}
      >
        {!photoPreview && (
          <div className="absolute inset-0 rounded-none bg-[#18181B]" />
        )}
        <div ref={previewRef} {...previewGestureProps}>
          {photoPreview ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              ref={photoImgRef}
              src={photoPreview}
              alt="Selected background"
              className="absolute h-full w-full origin-center object-cover"
              style={{
                transform: `translate3d(${photoTransform.offsetX}px, ${photoTransform.offsetY}px, 0) scale(${photoTransform.scale})`,
              }}
              draggable={false}
              data-capture-ignore="true"
            />
          ) : null}
          {photoPreview ? (
            <div
              className="absolute inset-0"
              style={{ background: `rgba(0, 0, 0, ${overlayOpacity})` }}
              data-capture-ignore="true"
            />
          ) : null}
          <MatchResultStandingsOverlay
            eventName={eventName}
            standingsType={standingsType}
            top3={top3}
          />
        </div>
      </div>

      {photoPreview ? (
        <p className="text-center text-xs text-[#71717A]">
          Pinch to resize, drag to move
        </p>
      ) : null}

      <button
        type="button"
        onClick={handleSelectPhotoClick}
        className="w-full rounded-full text-sm font-semibold text-[#18181B]"
        style={{ background: "#F4F4F5", height: "56px" }}
      >
        Select photos
      </button>

      <button
        type="button"
        onClick={handleShare}
        disabled={isSubmitting}
        className="w-full rounded-full text-base font-semibold text-[#121212] disabled:cursor-not-allowed disabled:opacity-50"
        style={{ background: "#9FE870", height: "56px" }}
      >
        {isSubmitting ? "Generating…" : "Share"}
      </button>

      {photoError ? (
        <p className="-mt-2 text-xs text-red-500">{photoError}</p>
      ) : null}

      {photoPreview ? (
        <div className="flex flex-col gap-2">
          <label
            htmlFor="match-overlay-opacity"
            className="text-sm font-medium text-[#18181B]"
          >
            Opacity: {Math.round(overlayOpacity * 100)}%
          </label>
          <input
            id="match-overlay-opacity"
            type="range"
            min={0}
            max={80}
            value={Math.round(overlayOpacity * 100)}
            onChange={(e) => setOverlayOpacity(Number(e.target.value) / 100)}
            className="w-full accent-[#9FE870]"
          />
        </div>
      ) : null}

      <input
        ref={fileInputRef}
        type="file"
        accept="image/jpeg,image/png,image/webp"
        className="hidden"
        onChange={handlePhotoChange}
      />
    </main>
  );
}
