import type { EventStandingsType } from "@/types/event";

export interface ShareStandingRow {
  rank: number;
  name: string;
  mp: number;
  wins: number;
  scoreDiff: number;
  winPct: string;
  total_points: number;
}

interface ShareImageBaseOptions {
  eventName: string;
  standingsType: EventStandingsType;
}

interface Top3ShareImageOptions extends ShareImageBaseOptions {
  top3: ShareStandingRow[];
}

interface YourResultShareImageOptions {
  eventName: string;
  yourRank: string;
  row: ShareStandingRow;
}

const WIDTH = 1080;
const HEIGHT = 1080;
const YOUR_RESULT_WIDTH = 1080;
const YOUR_RESULT_HEIGHT = 1000;
const GREEN = "#9FE870";
const GREEN_DARK = "#2E6900";
const TEXT_PRIMARY = "#18181B";
const TEXT_MUTED = "#71717A";
const MEDAL_COLORS = ["#EAB308", "#A1A1AA", "#FB923C"];

async function ensureLexendFont() {
  if (!document.fonts) return;
  await Promise.all([
    document.fonts.load('400 24px "Lexend"'),
    document.fonts.load('400 28px "Lexend"'),
    document.fonts.load('600 24px "Lexend"'),
    document.fonts.load('600 32px "Lexend"'),
    document.fonts.load('700 48px "Lexend"'),
    document.fonts.load('700 52px "Lexend"'),
    document.fonts.load('900 56px "Lexend"'),
    document.fonts.load('900 72px "Lexend"'),
  ]);
}

function standingsTypeLabel(type: EventStandingsType) {
  return type === "wins" ? "Most Wins" : "Point Difference";
}

function formatScoreDiff(value: number) {
  if (value > 0) return `+${value}`;
  return String(value);
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
) {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

function drawBrandHeader(
  ctx: CanvasRenderingContext2D,
  eventName: string,
  subtitle: string,
) {
  roundRect(ctx, 64, 64, WIDTH - 128, 220, 48);
  ctx.fillStyle = GREEN;
  ctx.fill();

  ctx.fillStyle = GREEN_DARK;
  ctx.font = '900 44px "Lexend", sans-serif';
  ctx.fillText("RALLYRANK", 104, 132);

  ctx.font = '700 40px "Lexend", sans-serif';
  const title = eventName.length > 28 ? `${eventName.slice(0, 27)}…` : eventName;
  ctx.fillText(title, 104, 188);

  ctx.font = '600 24px "Lexend", sans-serif';
  ctx.globalAlpha = 0.75;
  ctx.fillText(subtitle, 104, 232);
  ctx.globalAlpha = 1;
}

function drawMedal(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  rank: number,
) {
  const color = MEDAL_COLORS[rank - 1] ?? TEXT_MUTED;
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.moveTo(x, y);
  ctx.lineTo(x + 6, y + 10);
  ctx.lineTo(x + 12, y + 2);
  ctx.lineTo(x + 18, y + 10);
  ctx.lineTo(x + 24, y);
  ctx.lineTo(x + 20, y + 16);
  ctx.lineTo(x + 4, y + 16);
  ctx.closePath();
  ctx.fill();
}

function drawTop3Row(
  ctx: CanvasRenderingContext2D,
  row: ShareStandingRow,
  y: number,
  standingsType: EventStandingsType,
) {
  roundRect(ctx, 64, y, WIDTH - 128, 148, 36);
  ctx.fillStyle = "#FAFAFA";
  ctx.fill();

  ctx.strokeStyle = "#F4F4F5";
  ctx.lineWidth = 2;
  ctx.stroke();

  ctx.fillStyle = TEXT_PRIMARY;
  ctx.font = '700 40px "Lexend", sans-serif';
  ctx.fillText(String(row.rank), 104, y + 58);

  if (row.rank <= 3) {
    drawMedal(ctx, 148, y + 38, row.rank);
  }

  ctx.font = '600 34px "Lexend", sans-serif';
  const name = row.name.length > 22 ? `${row.name.slice(0, 21)}…` : row.name;
  ctx.fillText(name, 196, y + 58);

  ctx.font = '400 26px "Lexend", sans-serif';
  ctx.fillStyle = TEXT_MUTED;
  ctx.fillText(`MP ${row.mp}`, 104, y + 108);

  ctx.fillStyle = GREEN_DARK;
  ctx.font = '700 30px "Lexend", sans-serif';
  const stat =
    standingsType === "wins"
      ? `${row.wins} W · ${formatScoreDiff(row.scoreDiff)} · ${row.winPct}`
      : `${row.total_points} pts`;
  ctx.fillText(stat, 280, y + 108);
}

export async function generateTop3StandingsPng(
  options: Top3ShareImageOptions,
): Promise<Blob> {
  await ensureLexendFont();

  const canvas = document.createElement("canvas");
  canvas.width = WIDTH;
  canvas.height = HEIGHT;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Could not create image.");

  ctx.clearRect(0, 0, WIDTH, HEIGHT);

  drawBrandHeader(
    ctx,
    options.eventName,
    `Top 3 · ${standingsTypeLabel(options.standingsType)}`,
  );

  options.top3.forEach((row, index) => {
    drawTop3Row(ctx, row, 320 + index * 168, options.standingsType);
  });

  ctx.fillStyle = TEXT_MUTED;
  ctx.font = '400 24px "Lexend", sans-serif';
  ctx.textAlign = "center";
  ctx.fillText("Generated by RallyRank", WIDTH / 2, HEIGHT - 56);
  ctx.textAlign = "left";

  return canvasToPngBlob(canvas);
}

function drawPerformanceStat(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  label: string,
  value: string,
) {
  ctx.textAlign = "center";
  ctx.fillStyle = "rgba(255,255,255,0.72)";
  ctx.font = '600 24px "Lexend", sans-serif';
  ctx.fillText(label.toUpperCase(), x + width / 2, y);

  ctx.fillStyle = "#FFFFFF";
  ctx.font = '700 52px "Lexend", sans-serif';
  ctx.fillText(value, x + width / 2, y + 64);
  ctx.textAlign = "left";
}

function drawPerformanceStatsGrid(
  ctx: CanvasRenderingContext2D,
  stats: { label: string; value: string }[],
  startY: number,
) {
  const columns = 3;
  const colWidth = YOUR_RESULT_WIDTH / columns;
  const rowGap = 132;

  stats.forEach((stat, index) => {
    const col = index % columns;
    const row = Math.floor(index / columns);
    drawPerformanceStat(
      ctx,
      col * colWidth,
      startY + row * rowGap,
      colWidth,
      stat.label,
      stat.value,
    );
  });
}

export async function generateYourResultPng(
  options: YourResultShareImageOptions,
): Promise<Blob> {
  await ensureLexendFont();

  const canvas = document.createElement("canvas");
  canvas.width = YOUR_RESULT_WIDTH;
  canvas.height = YOUR_RESULT_HEIGHT;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Could not create image.");

  ctx.clearRect(0, 0, YOUR_RESULT_WIDTH, YOUR_RESULT_HEIGHT);

  const totalLoss = Math.max(0, options.row.mp - options.row.wins);
  const playerName =
    options.row.name.length > 28
      ? `${options.row.name.slice(0, 27)}…`
      : options.row.name;
  const eventName =
    options.eventName.length > 34
      ? `${options.eventName.slice(0, 33)}…`
      : options.eventName;

  ctx.textAlign = "center";
  ctx.fillStyle = "rgba(255,255,255,0.8)";
  ctx.font = '600 26px "Lexend", sans-serif';
  ctx.fillText(eventName, YOUR_RESULT_WIDTH / 2, 300);
  ctx.fillText(playerName, YOUR_RESULT_WIDTH / 2, 344);

  ctx.fillStyle = "#FFFFFF";
  ctx.font = '900 72px "Lexend", sans-serif';
  ctx.fillText("RALLYRANK", YOUR_RESULT_WIDTH / 2, 440);

  drawPerformanceStatsGrid(
    ctx,
    [
      { label: "Win Rate", value: options.row.winPct },
      { label: "Position", value: `#${options.yourRank}` },
      { label: "Matches Played", value: String(options.row.mp) },
      { label: "Total Win", value: String(options.row.wins) },
      { label: "Total Loss", value: String(totalLoss) },
      { label: "Total Points", value: String(options.row.total_points) },
    ],
    488,
  );

  ctx.strokeStyle = "#FFFFFF";
  ctx.lineWidth = 4;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  const iconX = YOUR_RESULT_WIDTH / 2;
  const iconY = YOUR_RESULT_HEIGHT - 72;
  ctx.beginPath();
  ctx.arc(iconX - 18, iconY - 8, 14, 0, Math.PI * 2);
  ctx.moveTo(iconX + 6, iconY - 20);
  ctx.lineTo(iconX + 34, iconY + 8);
  ctx.lineTo(iconX - 2, iconY + 8);
  ctx.closePath();
  ctx.stroke();

  ctx.textAlign = "left";

  return canvasToPngBlob(canvas);
}

function canvasToPngBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("Failed to generate image."));
    }, "image/png");
  });
}

export function downloadPng(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
